/**Copyright (C) 2013 Thomas Maher
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

package com.jimsuplee.deadshowfinder;

import android.app.ListActivity;
import android.app.Activity;
import android.content.Intent;
import android.widget.ListView;
import android.widget.ArrayAdapter;
import java.util.ArrayList;
import java.util.List;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.net.Uri;
import android.widget.TextView;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.view.View;
import android.util.Log;

public class Location  extends ListActivity {
	
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
	    displayListView();
	}

    private void displayListView() {
	    List<String> locationList = new ArrayList<String>();
        locationList.add("Aarhus University, Aarhus, XDEN");
        locationList.add("Academy of Music, New York, NY");
        locationList.add("Adams Field House (U of Montana), Missoula, MT");
        locationList.add("Aladdin Theater, Las Vegas, NV");
        locationList.add("Alexandra Palace, London, XE");
        locationList.add("Alfond Arena (U of Maine), Orono, ME");
        locationList.add("Allan Kirby Field House (Lafayette College), Easton, PA");
        locationList.add("Alligator Alley Gum (U of Florida), Gainesville, FL");
        locationList.add("Alpine Valley East Troy, Wis.");
        locationList.add("Alpine Valley East Troy,Wis.");
        locationList.add("Alpine Valley Music Theater, East Troy, WI");
        locationList.add("Alpine Valley Music Theatre, East Troy WI");
        locationList.add("Alumni Stadium (U of Mass), Amherst, MA");
        locationList.add("American University, Washington, DC");
        locationList.add("Anaheim Stadium, Anaheim, CA");
        locationList.add("Arena (U of Southern Illinois), Carbondale, IL");
        locationList.add("Arizona State University, Tempe, AZ");
        locationList.add("Arlington Theater, Santa Barbara, CA");
        locationList.add("Arrowhead Stadium, Kansas City, MO");
        locationList.add("Assembly Center (Lousiana State U), Baton Rouge, LA");
        locationList.add("Assembly Hall (Indiana U), Bloomington, IN");
        locationList.add("Assembly Hall (University of Illinois), Champlain, IL");
        locationList.add("Assembly Hall (U of Illinois), Champaign-Urbana, IL");
        locationList.add("Athletic Center (Rutgers U), New Brunswick, NJ");
        locationList.add("Auditorium Coliseum, Jacksonville, FL");
        locationList.add("Auditorium, St. Paul, MN");
        locationList.add("Auditorium Theater, Chicago, IL");
        locationList.add("Auditorium Theatre, Chicago, Ill");
        locationList.add("Auditorium Theatre, Chicago, ILL");
        locationList.add("Auditorium, West Palm Beach, FL");
        locationList.add("Augusta Civic Center, Augusta, ME");
        locationList.add("Autzen Stadium, Eugene, Or.");
        locationList.add("Autzen Stadium, Eugene, OR");
        locationList.add("Autzen Stadium, Eugene OR");
        locationList.add("Autzen Stadium, Eugene, OR");
        locationList.add("Autzen Stadium (U of Oregon), Eugene, OR");
        locationList.add("Bakersfield Civic Auditorium, Bakersfield, CA");
        locationList.add("Baltimore Civic Center, Baltimore, MD");
        locationList.add("Barton Hall (Cornell U), Ithica, NY");
        locationList.add("Bayfront Center   St. Petersburg, FL");
        locationList.add("Beacon Theatre, New York, NY");
        locationList.add("Beat Club, Bremen, XWGER");
        locationList.add("Berkeley Community Theater, Berkeley, CA");
        locationList.add("Berkeley Community Theatre, Berkeley, CA");
        locationList.add("Berkeley Greek Theatre");
        locationList.add("Bickershaw Festival, Wigan, XENG");
        locationList.add("Billerica Forum, Billerica, MA");
        locationList.add("Blossom Music Center, Cuyahoga Falls, OH");
        locationList.add("Bob Marley Performing Arts Center, Montego Bay, XJ");
        locationList.add("Boise Pavillion, Boise, ID");
        locationList.add("Boreal Ridge Ski Resort, Donners Summit, CA");
        locationList.add("Boston Garden, Boston, MA");
        locationList.add("Boston Music Hail, Boston, MA");
        locationList.add("Boston Music Hall, Boston, MA");
        locationList.add("Boston Music Hall, Boston, Mass");
        locationList.add("Boston Music Hall, Boston, Mass.");
        locationList.add("Boston Music Mall, Boston, MA");
        locationList.add("Boutwell Auditorium, Birmingham, AL");
        locationList.add("Brendan Byrne Arena");
        locationList.add("Brendan Byrne Arena, East Rutherford NJ");
        locationList.add("Brendan Byrne Arena, East Rutherford, NJ");
        locationList.add("Broome County Arena, Binghamton, NY");
        locationList.add("Buckeye Lake, Hebron OH");
        locationList.add("Buckeye Lake Music Center, Hebron, OH");
        locationList.add("Buckeye Music Center, Buckeye Lake OH");
        locationList.add("Calavaras County Fairgrounds, Angels Camp, CA");
        locationList.add("Cal Expo, Sacramento, CA");
        locationList.add("Cal Expo, Sacramento CA");
        locationList.add("Cal Expo, Sacramento, CA");
        locationList.add("California Exposition Amphitheater, Sacramento, CA");
        locationList.add("Cal State Dominguez Hills, Carson, CA");
        locationList.add("Cal State Dominguez Hills, Carson, CAput Line 0 of Field");
        locationList.add("Cameron Indoor Stadium (Duke U), Durham, NC");
        locationList.add("Cameron Indoor Stadium, Duke U, Durham, NC");
        locationList.add("Cameron Indoor Stadium Duke Univ., Durham, NC");
        locationList.add("Campus Stadium (UC Santa Barbara), Goleta, CA");
        locationList.add("Cap Center");
        locationList.add("Cap Centre, Landover");
        locationList.add("Cape Cod Coliseum, South Yarmouth, MA");
        locationList.add("Capital Centre, Landover, MD");
        locationList.add("Capitol Center, Landover, MD");
        locationList.add("Capitol Centre, Landover MD");
        locationList.add("Capitol Theater, Passaic, NJ");
        locationList.add("Capitol Theatre, Passaic, NJ");
        locationList.add("Cardinal Stadium, Louisville KY");
        locationList.add("Carolina Coliseum (U of South Carolina), Columbia, SC");
        locationList.add("Carrier Dome (Syracuse U), Syracuse, NY");
        locationList.add("Carter Finley, Raleigh NC");
        locationList.add("Centrum, Worcester MA");
        locationList.add("Charlotte Coliseum, Charlotte NC");
        locationList.add("Charlotte Coliseum, Charlotte, NC");
        locationList.add("Charlotte NC");
        locationList.add("Chrysler Arena, Ann Arbor MI");
        locationList.add("Chrysler Arena (U of Michigan), Ann Arbor, MI");
        locationList.add("Cincinnati Gardens, Cincinnati, OH");
        locationList.add("City Hall, Newcastle, XENG");
        locationList.add("City Island, Harrisburg, PA");
        locationList.add("Civic Arena, Pittsburgh PA");
        locationList.add("Civic Arena, Pittsburgh, PA");
        locationList.add("Civic Auditorium, Omaha, NB");
        locationList.add("Civic Auditorium, SanAntonio, TX");
        locationList.add("Civic Auditorium, San Jose, CA");
        locationList.add("Civic Center Arena, Springfield, MA");
        locationList.add("Civic Center, Baltimore, MD");
        locationList.add("Civic Center, Hartford CT");
        locationList.add("Civic Center, Providence, RI");
        locationList.add("Civic Center, Roanoke, VA");
        locationList.add("Civic Hall, Rotterdam, XNETHER");
        locationList.add("Cleveland Music Hall, Cleveland, OH");
        locationList.add("Cleveland Public Hall, Cleveland, OH");
        locationList.add("Club Melk Weg, Amsterdam, XH");
        locationList.add("COBO Arena, Detroit, MI");
        locationList.add("COBO Arena, Detroit, Mich.");
        locationList.add("Cole Field House (U of Maryland), College Park, MD");
        locationList.add("Coliseum, Charlotte, NC");
        locationList.add("Coliseum, Hampton VA");
        locationList.add("Colt Park, Hartford, Conn.");
        locationList.add("Community War Memorial, Rochester, NY");
        locationList.add("Compton Terrace Amphitheater, Tempe, AZ");
        locationList.add("Compton Terrace, Tempe AZ");
        locationList.add("Compton Terrace, Tempe, AZ");
        locationList.add("Concertgebouw, Amsterdam, XNETHER");
        locationList.add("Convention Center, Cleveland, OH");
        locationList.add("Copps Coliseum, Hamilton ON");
        locationList.add("Copps Coliseum, Hamilton, Ontario");
        locationList.add("Cotterrell Gym (Colgate U), Hamilton, NY");
        locationList.add("County Coliseum, El Paso, TX");
        locationList.add("Cow Palace, Daly City, CA");
        locationList.add("Cumberland County Civic Center, Portland, ME");
        locationList.add("Curtis Hixon Convention Hall, Tampa, FL");
        locationList.add("Dallas Convention Center, Dallas, TX");
        locationList.add("Dane County Coliseum, Madison, WI");
        locationList.add("Deer Creek IN");
        locationList.add("Deer Creek Music Center, Noblesville, IN");
        locationList.add("Deer Creek, Noblesville IN");
        locationList.add("Denver Coliseum, Denver, CO");
        locationList.add("Des Moines Civic Center, Des Moines, IA");
        locationList.add("Deutsches Museum Halle, Munich, XWGER");
        locationList.add("Devore Field (Southwestern U), Chula Vista, CA");
        locationList.add("Dijon, France");
        locationList.add("Dillon Stadium, Hartford, CT");
        locationList.add("Edmundson Pavilion (U of Washington), Seattle, WA");
        locationList.add("Empire Pool, Wembley, XENG");
        locationList.add("Events Center (U of Colorado), Boulder, CO");
        locationList.add("Fairgrounds Arena, Oklahoma City, OK");
        locationList.add("Fairgrounds, Lille, XFRA");
        locationList.add("Festhalle, Frankfurt, Germany");
        locationList.add("Feyline Field, Tempe, AZ");
        locationList.add("Field House (Northern Illinois U), De Kalb, IL");
        locationList.add("Field House (Rensselaer Polytechnic Institute), Troy, NY");
        locationList.add("Field House (Seneca College), Toronto, XCON");
        locationList.add("Fiesta Hall (County Fairgrounds), San Mateo, CA");
        locationList.add("Five Seasons Center, Cedar Rapids, IA");
        locationList.add("Folsom Field, University of Colorado, Boulder, CO");
        locationList.add("Folsom Field (U of Colorado), Boulder, CO");
        locationList.add("Ford Auditorium, Detroit, MI   			");
        locationList.add("Forum, Los Angeles CA");
        locationList.add("Forum Theater, Copenhagen, XD");
        locationList.add("Foxboro Sullivan");
        locationList.add("Fox Theater, Atlanta, GA");
        locationList.add("Fox Theatre, St. Louis, MO");
        locationList.add("Freedom Hall, Louisville KY");
        locationList.add("Freedom Hall, Louisville, KY");
        locationList.add("Freedom Hall, Lousville, KY");
        locationList.add("Frost Amphitheater, Palo Alto, Ca.");
        locationList.add("Frost Amphitheater (Stanford U), Palo Alto, CA");
        locationList.add("Frost Ampitheatre, Stanford CA");
        locationList.add("Frost Ampitheatre. Stanford, Calif.");
        locationList.add("Giants Stadium");
        locationList.add("Giants Stadium, East Rutherford NJ");
        locationList.add("Giants Stadium, East Rutherford, NJ");
        locationList.add("Giants Stadium (Meadowlands Sports Complex), East Rutherford, NJ");
        locationList.add("Glen Helen Regional Park, Devore, CA");
        locationList.add("Glenns Falls Civic Center, Glenns Falls, NY");
        locationList.add("Golden Hall, San Diego, CA");
        locationList.add("Grand Center, Grand Rapids, MI");
        locationList.add("Grand Prix Racecourse, Watkins Glen, NY");
        locationList.add("Great American Music Hall, San Francisco, CA");
        locationList.add("Greek Theater (U of California), Berkeley, CA");
        locationList.add("Greek Theatre, Berkeley CA");
        locationList.add("Greensboro Coliseum, Greensboro NC");
        locationList.add("Greensboro Coliseum, Greensboro, NC");
        locationList.add("Gruga Halle, Essen, West Germany");
        locationList.add("Gruga Halle, Essen, XG");
        locationList.add("Hampton Coliseum, Hampton VA");
        locationList.add("Hampton Roads Coliseum, Hampton, VA");
        locationList.add("Hara Arena, Dayton, OH");
        locationList.add("Hartford Civic Center Hartford CT");
        locationList.add("Hartford Civic Center, Hartford, CT");
        locationList.add("Henry J. Kaiser Auditorium, Oakland, CA");
        locationList.add("Henry J. Kaiser Auditorium, Oakland, CA.");
        locationList.add("Henry J. Kaiser Convention Center - Chinese New Year");
        locationList.add("Henry J. Kaiser Convention Center (Mardi Gras)");
        locationList.add("Henry J. Kaiser Convention Center, Oakland, CA");
        locationList.add("Henry J Kaiser, Oakland, CA");
        locationList.add("Hershey Park Stadium, Hershey, PA");
        locationList.add("Hile High Stadium, Denver, CO");
        locationList.add("HJK");
        locationList.add("Hofheinz Pavilion, Houston, TX");
        locationList.add("Holleder Stadium, Rochester, NY");
        locationList.add("Hollywood Bowl, Hollywood, CA");
        locationList.add("Hollywood Bowl, Los Angeles, CA");
        locationList.add("Hollywood Palladium, Hollywood, CA");
        locationList.add("Horton Field House (Illinois State U), Normal, IL");
        locationList.add("Hubert H. Humphrey Metrodome, Minniapolis, MN");
        locationList.add("Huntington Civic Center, Huntington, WV");
        locationList.add("I.C.C., Berlin, Germany");
        locationList.add("Indianapolis Convention Center, Indianapolis, IN");
        locationList.add("International Amphiteater, Chicago, IL");
        locationList.add("International Amphitheater, Chicago, IL");
        locationList.add("Irvine Meadows Amphitheater, Laguna Hills, CA");
        locationList.add("Irvine Meadows,  CA");
        locationList.add("Irvine Meadows, Irvine CA");
        locationList.add("Istadium, Stockholm, Sweeden");
        locationList.add("Jahrhundert Halle, Frankfurt, XWGER");
        locationList.add("Jai-Alai Fronton, Miami, FL");
        locationList.add("JFK Stadium, Philadelphia, PA");
        locationList.add("Joe Louis Arena, Detroit");
        locationList.add("Kansas City Municipal Auditorium, Kansas City, MO");
        locationList.add("Kezar Stadium, San Francisco, CA");
        locationList.add("Kiel Auditorium, St. Louis, MO");
        locationList.add("Kingswood Music Theater, Toronto, XCON");
        locationList.add("Kingswood Theater, Maple, XCON");
        locationList.add("Knickerbocker Arena, Albany, NY");
        locationList.add("Knickerbocker Arena, Albany NY");
        locationList.add("Knickerbocker Arena, Albany, NY");
        locationList.add("LA Forum");
        locationList.add("Laguna Seca");
        locationList.add("Laguna Seca Raceway, Monterey, CA");
        locationList.add("Lakefront Arena, University of New Orleans,  New Orleans, LA");
        locationList.add("Lakeland Civic Center, Lakeland, FL");
        locationList.add("L.A. Memorial Coliseum, Los Angeles, CA");
        locationList.add("Lindley Meadows (Golden Gate Park), San Francisco, CA");
        locationList.add("Lloyd Noble Center (U of Oklahoma), Norman, OK");
        locationList.add("Long Beach");
        locationList.add("Long Beach Arena");
        locationList.add("Long Beach Arena, Long Beach, CA");
        locationList.add("Los Angeles Sports Arena, Los Angeles, CA");
        locationList.add("Loyola College, Chicago, IL");
        locationList.add("Madison Square Garden, New York, NY");
        locationList.add("Madison Square Garden, NYC, NY");
        locationList.add("Manor Downs, Austin, TX");
        locationList.add("Marin County Veterans Auditorium, San Rafael, CA");
        locationList.add("Market Square Arena, Indianapolis, IN");
        locationList.add("Market Square Arena, Indianapolis, Ind.");
        locationList.add("Masonic Temple, Detroit, MI");
        locationList.add("McArthur Court (U of Oregon), Eugene, OR");
        locationList.add("McGaw Memorial Hall, Northwestern U., Evanston, IL");
        locationList.add("McNichols Arena, Denver CO");
        locationList.add("McNichols Arena, Denver, CO");
        locationList.add("McNichols Sports Arena, Denver, CO");
        locationList.add("Meadowlands Arena");
        locationList.add("Memorial Auditorium, Dallas, TX");
        locationList.add("Memorial Auditorium, Sacramento, CA");
        locationList.add("Memorial Auditorium, Utica, NY");
        locationList.add("Memorial Coliseum, Portland, OR");
        locationList.add("Memorial Coliseum (State Fairgrounds), Jackson, MS");
        locationList.add("Memorial Coliseum (U of Alabama), Tuscaloosa, AL");
        locationList.add("Memorial Hall, Kansas City, MO");
        locationList.add("Merriweather Post Pavilion, Columbia, MD");
        locationList.add("Met Center, Minneapolis MN");
        locationList.add("Metropolitan Center, Minneapolis, MN");
        locationList.add("Metropolitan Sports Center, Bloomington, MN");
        locationList.add("Miami Arena, Miami Florida");
        locationList.add("Miami FL");
        locationList.add("Mill Valley Recreation Center, Mill Valley, CA");
        locationList.add("Milwaukee Auditorium, Milwaukee, WI");
        locationList.add("Mississippi River Festival, Edwardsville, IL");
        locationList.add("Moody Coliseum (SMU), Dallas, TX");
        locationList.add("Morgantown Civic Center, Morgantown, WV");
        locationList.add("Moscone Center, San Francisco, CA");
        locationList.add("Municipal Auditorium, Austin, TX");
        locationList.add("Music Mall, Cincinnati, OH");
        locationList.add("Musikhalle, Hamburg, XWGER");
        locationList.add("Nashville Municipal Auditorium, Nashville, TN");
        locationList.add("Nassau Coliseum, Uniondale, NY");
        locationList.add("Nassau Coliseum, Uniondale NY");
        locationList.add("Nassau Coliseum, Uniondale, NY");
        locationList.add("Nassau Coliseum, Uniondale NY (Marsalis)");
        locationList.add("Nassau Coliseum, Uniondale, NY");
        locationList.add("Nassau Veterans Memorial Coliseum, Uniondale , NY");
        locationList.add("Nassau Veterans Memorial Coliseum, Uniondale, NY");
        locationList.add("NBC Studios, New York, NY");
        locationList.add("NBC Studios, New York, NY_Comments: Letterman_JG, BW_");
        locationList.add("NBC Studios, New York, NY _Comments: the Tomorrow Show_");
        locationList.add("Nevada County Fairgrounds, Grass Valley, CA");
        locationList.add("Niagara Falls Convention Center, Niagara Falls, NY");
        locationList.add("Oakland-Alameda County Stadium, Oakland CA");
        locationList.add("Oakland Arena");
        locationList.add("Oakland Auditorium Arena, Oakland, CA");
        locationList.add("Oakland Coliseum");
        locationList.add("Oakland Coliseum Arena");
        locationList.add("Oakland Coliseum Arena, Oakland, CA");
        locationList.add("Oakland Coliseum, Oakland, CA");
        locationList.add("Oakland Coliseum,  Oakland CA");
        locationList.add("Oakland Coliseum,  Oakland, CA");
        locationList.add("Oakland Coliseum, Oakland CA");
        locationList.add("Oakland Coliseum, Oakland, CA");
        locationList.add("Oakland Coliseum, Oakland, CA - NYE");
        locationList.add("Oakland Coliseum, Oakland, CA");
        locationList.add("Oakland Coliseum Stadium, Oakland, CA");
        locationList.add("Oklahoma City Music Hall, Oklahoma City, OK");
        locationList.add("Old Renaissance Faire Grounds, Veneta, OR");
        locationList.add("Olympia Halle, Munich, XG");
        locationList.add("Olympia Theater, Paris, XFRA");
        locationList.add("Olympic Center, Lake Placid, NY");
        locationList.add("Omaha Auditorium, Omaha, NE");
        locationList.add("Omni Coliseum, Atlanta, GA");
        locationList.add("Onondaga County War Memorial, Syracuse, NY");
        locationList.add("Onondaga War Memorial Auditorium, Syracuse, NY");
        locationList.add("Onondaga War Memorial Aud., Syracuse, NY");
        locationList.add("Orchard Park Rich");
        locationList.add("Oregon County Fair Site, Veneta, OR");
        locationList.add("Orlando Arena, Orlando, FL");
        locationList.add("Orpheum Theatre, San Francisco, CA");
        locationList.add("Oxford Plains Speedway");
        locationList.add("Palais Des Sports, Paris, France");
        locationList.add("Palais Des Sports, Paris, XF");
        locationList.add("Paramount Northeast, Seattle, WA");
        locationList.add("Paramount Northwest, Seattle, WA");
        locationList.add("Paramount Northwest Theatre, Seattle, WA");
        locationList.add("Paramount Theater, Portland, OR");
        locationList.add("Paramount Theatre, Portland, Ore.");
        locationList.add("Park West Ski Resort, Salt Lake City, UT");
        locationList.add("Patrick Field House (U of Vermont), Burlington, VT");
        locationList.add("Pauley Pavilion (UCLA), Los Angeles, CA");
        locationList.add("Pauley Pavilion, U.C.L.A., Los Angeles, CA");
        locationList.add("Pavilion (U Illinois At Chicago), Chicago, IL");
        locationList.add("Performing Arts Center, Milwaukee, WI");
        locationList.add("Pershing Municipal Auditorium, Lincoln, NB");
        locationList.add("Philadelphia Civic Center, Philadelphia, PA");
        locationList.add("Philadelphia JFK");
        locationList.add("Philadelphia Spectrum");
        locationList.add("Pine Knob Music Theater, Clarkstown, MI");
        locationList.add("Pine Knob Music Theatre, Clarkston, MI");
        locationList.add("Pittsburg");
        locationList.add("Pittsburgh Civic Arena, Pittsburgh, PA");
        locationList.add("Playhouse Theater, Edinburgh, XS");
        locationList.add("P.N.E, Coliseum, Vancouver, BC, XCAN");
        locationList.add("P.N.E. Coliseum, Vancouver, XCBC");
        locationList.add("Polo Field, Golden Gate Park, San Francisco, CA");
        locationList.add("Poplar Creek Pavilion, Poplar Creek, IL");
        locationList.add("Portland International Speedway, Portland, OR");
        locationList.add("Portland Memorial Coliseum, Portland, OR");
        locationList.add("Providence Civic Center, Providence, RI");
        locationList.add("Public Hall, Cleveland, OH");
        locationList.add("Raceway Park, Englishtown, NJ");
        locationList.add("Radio City Music Hall, New York, NY");
        locationList.add("Radio Luxembourg, XLUX");
        locationList.add("Rainbow Theater, London, XE");
        locationList.add("Rec Hall (Penn State U), State College, PA");
        locationList.add("Recreation Hall (UC Davis), Davis, CA");
        locationList.add("Red Rocks Amphitheater, Morrison, CO");
        locationList.add("Reno Centennial Coliseum, Reno, NV");
        locationList.add("Reunion Arena,  Dallas TX");
        locationList.add("RFK Stadium, Washington DC");
        locationList.add("RFK Stadium, Washington, DC");
        locationList.add("Rheinhalle, Dusseldorf, XWGER");
        locationList.add("Richfield Coliseum, Richfield, OH");
        locationList.add("Richfield Coliseum, Richfield OH");
        locationList.add("Richfield Coliseum, Richfield, OH");
        locationList.add("Richmond Coliseum, Richmond, VA");
        locationList.add("Rich Stadium, Buffalo, NY");
        locationList.add("Rich Stadium, Orchard Park NY");
        locationList.add("Rich Stadium, Orchard Park, NY");
        locationList.add("River Bend Music Center, Cincinnati, OH");
        locationList.add("River Front Coliseum, Cincinatti, Oh.");
        locationList.add("Riverfront Coliseum, Cincinnati OH");
        locationList.add("Robert F. Kennedy Stadium, Washington, DC");
        locationList.add("Robertson Gym (UC Santa Barbara), Goleta, CA");
        locationList.add("Rochester Silver Stadium");
        locationList.add("Roosevelt Stadium, Jersey City, NJ");
        locationList.add("Roscoe Maples Pavilion (Stanford U), Palo Alto, CA");
        locationList.add("Rosemont Horizon");
        locationList.add("Rosemont Horizon, Chicago Il");
        locationList.add("Rosemont Horizon, Chicago Il.");
        locationList.add("Rosemont Horizon, Chicago, IL");
        locationList.add("Rosemont Horizon, Rosemont, IL");
        locationList.add("Rosemont Horizon, Rosemont IL");
        locationList.add("Rosemont Horizon, Rosemont, IL");
        locationList.add("Rubber Bowl, Akron, OH");
        locationList.add("Rupp Arena (Lexington Center), Lexington, KY");
        locationList.add("Sacramento Memorial Auditorium, Sacramento, CA");
        locationList.add("Saenger Performing Arts Center, New Orleans, LA");
        locationList.add("Salt Palace, Salt Lake City, UT");
        locationList.add("Sam Boyd Silver Bowl, Las Vegas, NV");
        locationList.add("Sam Boyd Silver Bowl, Las Vegas NV");
        locationList.add("San Diego Sports Areana, San Diego, CA");
        locationList.add("San Diego Sports Arena, San Diego, CA");
        locationList.add("Sandstone Aphitheatre, Bonner Springs, KS");
        locationList.add("Sandstone, Bonner Springs KS");
        locationList.add("San Francisco Civic, San Francisco, CA");
        locationList.add("Santa Cruz County Fairgrounds, Watsonville, CA");
        locationList.add("Santa Fe Downs, Santa Fe, NM");
        locationList.add("Saratoga Performing Arts");
        locationList.add("Saratoga Performing Arts Center, Saratoga Springs, NY");
        locationList.add("Saturday Night Live, NBC Studios, New York, NY");
        locationList.add("Seattle Center Arena, Seattle, WA");
        locationList.add("Seattle Center Coliseum, Seattle, WA");
        locationList.add("Selland Arena, Fresno, CA");
        locationList.add("Sheas Theater, Buffalo, NY");
        locationList.add("Shoreline Amphitheater");
        locationList.add("Shoreline Amphitheater, Mountain View CA");
        locationList.add("Shoreline Amphitheater, Mountain View, CA");
        locationList.add("Shoreline Ampitheatre");
        locationList.add("Shoreline Ampitheatre, Mountain View, CA");
        locationList.add("Shoreline Ampitheatre, Mountain View CA");
        locationList.add("Shoreline Ampitheatre, Mountain View, MA");
        locationList.add("Shoreline Ampitheatre, Mtn. View CA");
        locationList.add("Shoreline, Mountain View, CA");
        locationList.add("Shrine Auditorium, Los Angeles, CA");
        locationList.add("Silva Hall (Hult Center), Eugene, OR");
        locationList.add("Silver Stadium, Rochester, NY");
        locationList.add("Soldier Field, Chicago, IL");
        locationList.add("Soldiers and Sailors Memorial Hall, Kansas City, KS");
        locationList.add("Soldiers Field, Chicago, IL");
        locationList.add("Soldiers Field, Chicago IL");
        locationList.add("Son Et Lumiere Theater, Giza, XZ");
        locationList.add("Southern Star Amphitheater, Houston, TX");
        locationList.add("Spartan Stadium, San Jose, CA");
        locationList.add("Spokane Coliseum, Spokane, WA");
        locationList.add("Sportsahala, Hamburg, Germany");
        locationList.add("Sports and Music Center, Indianapolis, IN");
        locationList.add("Sports Palace, Barcelona, XP");
        locationList.add("Springfield Civic Center, Springfield, MA");
        locationList.add("Stabler Arena (Lehigh U), Bethlehem, PA");
        locationList.add("Stadium, U.C.S.B., Santa Barbara, CA");
        locationList.add("Stadt Halle, Bremen, XG");
        locationList.add("Stanley Theater, Pittsburgh, PA");
        locationList.add("Stanley Theatre, Jersey City, NJ");
        locationList.add("Star Lake Amphitheater, Burgettstown PA");
        locationList.add("Starlight Theater, Kansas City, MO");
        locationList.add("State Fair Coliseum, Indianapolis, IN");
        locationList.add("State Fairgrounds, Des Moines, IA");
        locationList.add("State Fairgrounds, Lewiston, ME");
        locationList.add("St. Johns Arena Ohio State Univ., Columbus, O.H.");
        locationList.add("St. Louis Arena, St. Louis, MO");
        locationList.add("Stockton Civic Aud., Stockton, CA");
        locationList.add("St. Paul Civic Center, St. Paul, MN");
        locationList.add("Studio Rehersal");
        locationList.add("Sullivan Stadium, Foxboro MA");
        locationList.add("Sullivan Stadium, Foxboro, MA");
        locationList.add("Summit Arena, Houston TX");
        locationList.add("Sun Dome, Tampa, FL");
        locationList.add("Swing Auditorium, San Bernardino, CA");
        locationList.add("Tacoma Dome, Tacoma, Wash.");
        locationList.add("The Centrum, Worcester MA");
        locationList.add("The Centrum, Worcester, MA");
        locationList.add("The Dean Dome, University of NC, Chapel Hill, NC");
        locationList.add("The Fabulous Forum, Inglewood, CA");
        locationList.add("The Greek Theatre, Berkeley CA");
        locationList.add("The Hippodrome, Paris, XF");
        locationList.add("The MECCA, Milwaukee WI");
        locationList.add("The Met Center Bloomington, Mn.");
        locationList.add("The Mosque, Richmond, VA");
        locationList.add("The Omni, Atlanta, GA");
        locationList.add("The Omni, Atlanta GA");
        locationList.add("The Omni, Atlanta, GA");
        locationList.add("The Palace, Auburn Hills, MI");
        locationList.add("The Palace, Auburn Hills MI");
        locationList.add("The Palace Theater, Waterbury, CT");
        locationList.add("The Palladium, New York, NY");
        locationList.add("The Sam Boyd Silver Bowl, Las Vegas, NV");
        locationList.add("The Scope, Norfolk, VA");
        locationList.add("The Spectrum, Philadelphia, PA");
        locationList.add("The Spectrum, Philadelphia PA");
        locationList.add("The Spectrum, Philadelphia, PA");
        locationList.add("The Sportatorium, Hollywood, FL");
        locationList.add("The Strand Lyceum, London, XENG");
        locationList.add("The Summit, Houston, TX");
        locationList.add("The Zenith, Paris, FR");
        locationList.add("Thompson Arena (Dartmouth College), Hanover, NH");
        locationList.add("Three Rivers Stadium, Pittsburgh PA");
        locationList.add("Tivoii Gardens, Copenhagen, XDEN");
        locationList.add("Tivoii Theater, Copenhagen, XDEN");
        locationList.add("Tower Theater, Upper Darby, PA");
        locationList.add("Tower Theatre, Upper Darby, PA");
        locationList.add("Town Park, Telluride, CO");
        locationList.add("Tulsa Fairgrounds Pavilion, Tulsa, OK");
        locationList.add("Uni Dome (University of Northern Iowa), Cedar Falls, IA");
        locationList.add("Universal Amphitheatre, Universal City, CA");
        locationList.add("University of Iowa, Iowa City, IA");
        locationList.add("University of Nevada, Reno, NV");
        locationList.add("University of New Mexico, Albuquerque, NM");
        locationList.add("University of Virginia, Charlottesville, VA");
        locationList.add("Uptown Theater, Chicago, IL");
        locationList.add("Utica Memorial Auditorium, Utica, NY");
        locationList.add("Utica Memorial Coliseum, Utica, NY");
        locationList.add("Vanderbilt University, Nashville, TN");
        locationList.add("Ventura County Fairgrounds, Ventura, CA");
        locationList.add("Veterans Memorial Auditorium, Columbus, OH");
        locationList.add("Veterans Memorial Coliseum (CT03?), Hartford, CT");
        locationList.add("Veterans Memorial Coliseum, New Haven, CT");
        locationList.add("Veterans Memorial Hall, Colombus, OH");
        locationList.add("Virginia Polytechnic University, Blacksburg, VA");
        locationList.add("Walter Koebel Halle, Russelsheim, XG");
        locationList.add("Warfield Theater, San Francisco, CA");
        locationList.add("Warfield Theater, San Francisco, CA_Comments: Nuclear Disarmament Benefit_JG, BW, MH, BK, BM, JKahn_");
        locationList.add("War Memorial Auditorium, Buffalo NY");
        locationList.add("War Memorial Auditorium, Buffalo, NY");
        locationList.add("War Memorial Auditorium, Rochester, NY");
        locationList.add("War Memorial Aud., Rochester, NY");
        locationList.add("Washington RFK");
        locationList.add("Wembley Arena, London, England");
        locationList.add("West High Auditorium, Anchorage, AK");
        locationList.add("Wichita, KS");
        locationList.add("William and Marry Hall, Williamsburg, VA");
        locationList.add("William and Mary College, Williamsburg, VA");
        locationList.add("William and Mary Hall, Williamsburg, VA");
        locationList.add("Winteriand Arena, San Francisco, CA");
        locationList.add("Winterland Arena, San Francisco, CA");
        locationList.add("World Amphitheatre, Tinley Park IL");
        locationList.add("Zoo Amphitheater, Oklahoma City, OK");
		// create an ArrayAdaptar from the String Array
		ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this, R.layout.locationtextview, locationList);
		setListAdapter(dataAdapter);
		ListView listView = getListView();
		// enables filtering for the contents of the given ListView
		listView.setTextFilterEnabled(true);
		listView.setOnItemClickListener(new OnItemClickListener() {
			public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
				Intent i = new Intent("");
				String locationChoice = ((TextView) view).getText().toString();			
				i.setData(Uri.parse(locationChoice));
				setResult(RESULT_OK, i);
				finish();
			}
		});
    }
}
